service: sms-api

provider:
  name: aws
  runtime: nodejs12.x
  profile: AdministratorAccess-321365023689
  region: ap-southeast-1

functions:
  sendSMS:
    handler: lambdas/endpoints/sendSMS.handler
    events:
      - http:
          path: send-sms
          method: post
          cors: true
